channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.9
  - snakemake=8.26
  - snakemake-storage-plugin-ftp
  - snakemake-storage-plugin-http
  - snakefmt>=0.10.0
  - pandas
  - biopython
  - pre-commit
  - gh
  - ipykernel
  - mail
