outdir: results
runsheet: config/runsheet.tsv
patientsheet: config/patientsheet.tsv

STARsolo:
  soloFeatures: # Gene=spliced only, GeneFull=spliced and unspliced, and Velocyto=spliced, unspliced, and ambiguous
    - Gene
    - GeneFull
    - Velocyto
  outFilterMultimapNmax: 100
  winAnchorMultimapNmax: 100
  soloMultiMappers: EM # EM, Uniform, PropUnique, or Rescue

use_CellBender: false
use_IRescue: true

preprocess:
  empty:
    min_genes: 200
  lowexp:
    min_cells: 3
  low_quality:
    activate: false
    min_counts: 1000
    max_pct_mt: 5
    min_genes: 100
