outdir: results
runsheet: config/runsheet.tsv # one 10x-run per row, with paths to fastq files and cell number information
patientsheet: config/patientsheet.tsv # one patient per row, with patient-specific information (ie disease-status, age, sex, etc)

# Mapping + Quantification
STARsolo:
  10x_protocol: 3prime_v3 # 5prime, 3prime_v3, or 3prime_v2
  soloFeatures: # Gene=spliced only, GeneFull=spliced and unspliced, and Velocyto=spliced, unspliced, and ambiguous
    - Gene
    - GeneFull
    - Velocyto
  outFilterMultimapNmax: 100
  winAnchorMultimapNmax: 100
  soloMultiMappers: EM # EM, Uniform, PropUnique, or Rescue

# CellBender is used to remove ambient RNA
# Runs very slowly without GPU
use_CellBender: false

# IRescue, uses alignments from STARsolo, is used to quantify TE expression
use_IRescue: true

# Parameters for filtering empty droplets, low-quanlity cells, and lowly-expressed genes
preprocess:
  empty:
    min_genes: 200
  lowexp:
    min_cells: 3
  low_quality:
    activate: false
    min_counts: 1000
    max_pct_mt: 5
    min_genes: 100
