outdir: /raidixshare_logg01/mcuoco/internal/jasmin_microglia/organoid_results
runsheet: config/imicrogliaORG2_runsheet.tsv # one 10x-run per row, with paths to fastq files and cell number information
patientsheet: config/imicroglia_patientsheet.tsv # one patient per row, with patient-specific information (ie disease-status, age, sex, etc)
genotypes: /raidixshare_logg01/mcuoco/internal/jasmin_microglia/clean_impute_snps/MichiganImputation_results/imputed/merged.dose.10xchrs.sorted.vcf

# Mapping + Quantification
10x_chemistry: 5prime # 5prime, 3prime_v3, or 3prime_v2
STARsolo:
  soloBarcodeReadLength: 101
  soloFeatures: # Gene=spliced only, GeneFull=spliced and unspliced, and Velocyto=spliced, unspliced, and ambiguous
    - GeneFull
    - Velocyto
  outFilterMultimapNmax: 100
  winAnchorMultimapNmax: 100
  soloMultiMappers: EM # EM, Uniform, PropUnique, or Rescue

# CellBender is used to remove ambient RNA
# Runs very slowly without GPU
use_CellBender: false

# IRescue, uses alignments from STARsolo, is used to quantify TE expression
use_IRescue: False

use_Demuxlet: True

# Parameters for filtering empty droplets, low-quality cells, and lowly-expressed genes
preprocess:
  min_counts: 1000
  max_pct_mt: 10
  min_genes: 1000
  signatures:
    - "cell_cycle_human"
    - "apoptosis_human"
    - "gender_human"
  regress_out:
    - "n_counts"
  resolutions:
    - 0.3
    - 0.4
    - 0.5
    - 0.6
