outdir: results
runsheet: config/runsheet.tsv
patientsheet: config/patientsheet.tsv

10x_chemistry: 3prime_v3 # 5prime, 3prime_v3, or 3prime_v2
STARsolo:
  soloFeatures:
    - Gene
    - GeneFull
    - Velocyto
  outFilterMultimapNmax: 100
  winAnchorMultimapNmax: 100
  soloMultiMappers: EM

use_CellBender: false
use_IRescue: true

preprocess:
  min_counts: 10
  min_genes: 10
  max_pct_mt: 10
  regress_out:
    - "n_counts"
    - "percent_mito"
