outdir: results
runsheet: config/runsheet.tsv
patientsheet: config/patientsheet.tsv

use_CellBender: false
use_IRescue: true

preprocess:
  empty:
    min_genes: 2
  lowexp:
    min_cells: 2
  low_quality:
    activate: true
    min_counts: 100
    max_pct_mt: 5
    min_genes: 50
