outdir: results
runsheet: config/runsheet.tsv
patientsheet: config/patientsheet.tsv

10x_chemistry: 3prime_v3 # 5prime, 3prime_v3, or 3prime_v2
STARsolo:
  soloFeatures:
    - Gene
    - GeneFull
    - Velocyto
  outFilterMultimapNmax: 100
  winAnchorMultimapNmax: 100
  soloMultiMappers: EM

use_CellBender: false
use_IRescue: true

preprocess:
  empty:
    min_genes: 2
  lowexp:
    min_cells: 2
  low_quality:
    activate: true      # TODO: prevent pipeline from running past filter step if activate==false
    min_counts: 100
    max_pct_mt: 5
    min_genes: 50
