$schema: "https://json-schema.org/draft/2020-12/schema"

description: snakemake configuration file

type: object

properties:
  outdir:
    type: string
    description: path to the output directory (does not need to exist)
  runsheet:
    type: string
    description: path to the runsheet
  patientsheet:
    type: string
    description: path to the patientsheet
  genotypes:
    type: string
    description: path to the genotypes file (vcf)
  10x_chemistry:
    type: string
    description: 10x chemistry used
    enum:
      - 5prime
      - 3prime_v3
      - 3prime_v2
  STARsolo:
    type: object
    description: some parameters for STARsolo
    required:
      - soloFeatures
      - outFilterMultimapNmax
      - winAnchorMultimapNmax
      - soloMultiMappers
    properties:
      soloFeatures:
        type: array
        description: features to be extracted by STARsolo
        items:
          type: string
          enum:
            - Gene
            - GeneFull
            - Velocyto
      outFilterMultimapNmax:
        type: integer
        description: maximum number of alignments to be considered for a read
      winAnchorMultimapNmax:
        type: integer
        description: maximum number of alignments to be considered for an anchor
      soloMultiMappers:
        type: string
        description: how to handle multi-mapping reads
        enum:
          - EM
          - Uniform
          - PropUnique
          - Rescue
  use_CellBender:
    type: boolean
    description: whether to use CellBender to correct the 10x data
  use_IRescue:
    type: boolean
    description: whether to use IRescue to quantify TE expression
  preprocess:
    type: object
    description: parameters for preprocessing the data
    required:
      - min_counts
      - max_pct_mt
      - min_genes
    min_counts:
      type: integer
      description: minimum number of counts in a cell
    max_pct_mt:
      type: number
      description: maximum percentage of mitochondrial counts in a cell
    min_genes:
      type: integer
      description: minimum number of genes detected in a cell
    signatures:
      type: array
      description: signatures to be calculated
      enum:
        - cell_cycle_human
        - apoptosis_human
        - gender_human
        - mitochondrial_genes_human
        - ribosomal_genes_human
    regress_out:
      type: array
      description: variables to be regressed out
    resolutions:
      type: array
      description: resolutions to run leiden clustering

required:
  - outdir
  - runsheet
  - patientsheet
  - genotypes
  - 10x_chemistry
  - use_CellBender
  - use_IRescue
  - preprocess
